
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
  labels:
    app: game-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      name: game-app
      labels:
        app: game-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: game-app
          image: jorgelfant/ipi-project
          imagePullPolicy: Always
          ports:
            - containerPort: 3003

---
apiVersion: v1
kind: Service
metadata:
  name: game-app
  labels:
    app: game-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      name: http
  selector:
    app: game-app

---

apiVersion: v1
kind: Service
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  selector:
    app: docker-mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  selector:
    matchLabels:
      app: docker-mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docker-mysql
    spec:
      containers:
        - image: mysql
          name: docker-mysql
          env:
            - name: MYSQL_DATABASE
              value: games
            - name: MYSQL_ROOT_PASSWORD
              value: test1234
            - name: MYSQL_ROOT_HOST
              value: '%'
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb-vol
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb-vol
          configMap:
            name: mysql-initdb-config


