apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app-deployment
  labels:
    app: game-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: game-app
          image: jorgelfant/ipi-project
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: test1234
            - name: MYSQL_DATABASE
              value: games

---

apiVersion: v1
kind: Service
metadata:
  name: game-app
  labels:
    run: game-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      name: http
  selector:
    app: game-app
---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test1234
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: test1234
            - name: MYSQL_DATABASE
              value: games
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
