apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app-deployment
  labels:
    app: game-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: game-app
          image: jorgelfant/ipi-project
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: test1234
            - name: MYSQL_DATABASE
              value: games

---

apiVersion: v1
kind: Service
metadata:
  name: game-app
  labels:
    run: game-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      name: http
  selector:
    app: game-app
---

apiVersion: v1
kind: Service
metadata:
  name: docker-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: docker-mysql
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql-deployment
  labels:
    app: docker-mysql
spec:
  selector:
    matchLabels:
      app: docker-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docker-mysql
    spec:
      containers:
        - image: mysql
          name: docker-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test1234
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: test1234
            - name: MYSQL_DATABASE
              value: games
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: docker-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: docker-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: docker-mysql-pv-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

